remove rustc --release flag
zerotier/ZeroTierOne pull request #2011
Opened 2023-05-19 17:43 UTC by mchangrh

The `--release` flag should be [applied to cargo, not rustc](https://stackoverflow.com/questions/45593026/unrecognized-option-release-when-compiling-with-rustc-in-release-mode). This causes the compiler to exit with code 1 since release is an unrecognized option.

Docker mcve against version 1.10.5 with [alpine](https://gitlab.alpinelinux.org/alpine/aports/-/commit/7f7b355d081655ed3fbbc6391f6aac987d2d4e2c)
```dockerfile
FROM alpine:edge

RUN apk update && \
    apk add --no-cache alpine-sdk wget && \
    addgroup root abuild

RUN mkdir "/root/.abuild"
RUN abuild-keygen -an
WORKDIR /build
RUN wget https://gitlab.alpinelinux.org/alpine/aports/-/raw/eab757ac9e60bc25cf5d0c5b07785b12e7a4bb04/community/zerotier-one/APKBUILD && \
    wget https://gitlab.alpinelinux.org/alpine/aports/-/raw/eab757ac9e60bc25cf5d0c5b07785b12e7a4bb04/community/zerotier-one/zerotier-one.initd
RUN abuild -F checksum && abuild -F -r
```

the patch can also be tested in docker
APKBUILD
```patch
source="$pkgname-$pkgver.tar.gz::https://github.com/zerotier/ZeroTierOne/archive/refs/tags/$pkgver.tar.gz
	$pkgname.initd
+	rustc-release.patch
	"
```

rustc-release.patch
```patch
diff -Nurp a/C/make-linux.mk b/C/make-linux.mk
--- a/make-linux.mk	2023-05-19 13:12:27.946482400 -0400
+++ b/make-linux.mk	2023-05-19 13:19:00.633535900 -0400
@@ -71,7 +71,7 @@ else
 	CXXFLAGS?=-O3 -fstack-protector
 	override CXXFLAGS+=-Wall -Wno-deprecated -std=c++17 -pthread $(INCLUDES) -DNDEBUG $(DEFS)
 	LDFLAGS=-pie -Wl,-z,relro,-z,now
-	RUSTFLAGS=--release
+	RUSTFLAGS=
 endif
 
 ifeq ($(ZT_QNAP), 1)
```

2023-05-19 17:57 UTC, glimberg requested changes
This change will prevent `--release` from being passed to the actual cargo build process.

https://github.com/zerotier/ZeroTierOne/blob/da71e2524c343f563ea9c37e9668eec7c5719aaa/make-linux.mk#L414

2023-05-19 18:46 UTC, mchangrh commented
> This change will prevent `--release` from being passed to the actual cargo build process.
> 
> https://github.com/zerotier/ZeroTierOne/blob/da71e2524c343f563ea9c37e9668eec7c5719aaa/make-linux.mk#L414

I have added `CARGOFLAGS` to explicitly pass options to cargo since `RUSTFLAGS` is passed to all compilers.

2023-05-19 19:20 UTC, glimberg requested changes
i'm really not sure what your goal is here.  The RUSTFLAGS variable in the makefile is only meant to pass flags to the cargo build process so that it will build a release library, or a debug library when compiling a debug version of ZeroTier

2023-05-19 19:23 UTC, glimberg commented
It's also works as is before this PR on all platforms we build for

2023-05-19 19:36 UTC, mchangrh commented
> i'm really not sure what your goal is here.

building zerotier on alpine linux fails since `--release` is passed in RUSTFLAGS to rustc, which causes it to fail with `error: Unrecognized option: 'release'`.

`--release` should only be passed to cargo or cargo-rustc, not in `RUSTFLAGS`.

2023-05-19 19:37 UTC, glimberg commented
Not sure what the difference is with Alpine vs the rest of the Linux distribution world, but this last change seems to change the intent, which is just a variable to hold flags to pass to cargo

2023-05-19 19:44 UTC, mchangrh commented
I'm currently testing between debian and alpine to try and figure out why the build is failing on one but not the other. The RUSTFLAGS environment variable/ config key is used to [pass flags to the compiler](https://doc.rust-lang.org/cargo/reference/config.html), not to cargo. The use of the RUSTFLAGS variable to pass the argument to cargo confused me.

```toml
rustflags = ["…", "…"]        # custom flags to pass to all compiler invocations
```

2023-07-06 19:32 UTC, glimberg commented
closing due to lack of activity from the reporter.

2023-07-06 19:32 UTC, closed without merging